language: cpp
matrix:
  include:
  - os: osx
  - os: linux
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-9
    env:
    - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
before_install:
- eval "${MATRIX_EVAL}"
script:
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=${HOME}/local ..
- cmake --build . -- --jobs=2
- cmake --build . --target install
- ctest -V
branches:
  except:
  - "/^v?\\d+\\.\\d+/"
notifications:
  email: false
  slack:
    secure: AeaMYoXZ7dWuKNa1N7MQuyPC1QPAitmmpyJpilfBMNik94TWYmVjluZ/DWbT2NVL+nLryXCXxqubRIv0bwN06b4wylOuG9oPPSqXhbCqrhJdSEt8BKknByt9Xa5GfQboY0dwHhA0PKK9JHICnUQz6QMNjAGI0iomI9tO6spwwn+oTvS5KBpq5BUwdSfb8uLbeSXZ8FsHCWlzsUV7BhI9+65ZkTfhzhqG+nXnyQCn9RX/Hl/TD/3KtvhpLoPt+69ons85FjNWQYmvCcPvNLNk8QzQOkzjkFoh9IbpYU1FfMdmcR76cGutUqe55wz9U8qOUZ4vieMguquoPDHc7pcHcVDlzGLRefdjozhv+5w/pLUO5yIIT18PfuTIkdZyxQFvap2y/VRgcP2YEpP0cq1oEWHlb9muaXrBhP79Wd+GKvC11BK+wcANI0FF5H8rr9T2k89CvlpjwELBfmkK7ERCUhUjIsVyd4LVxHcPmw+GCEAFotp5DoOuDVeSkKE0sNu1YRbaPzA3MaM/4fdDuDMeqBC0JchxyRiSY5UfGND7oS8sWIdpfv7VTOz9oy8Z7l8SzQXgLr1EBcJQmwXiP3pl1pkra1hTbjwS4hGAbltkrjTo3MXowEPU0AtbbroXO88C6fRQlCQJpepwCLkGzf/SiGqX/YMavFR0muxG03bp0pg=
